include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  language:
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_use_of_protected_member: error
    missing_required_param: error
    missing_return: error
    use_build_context_synchronously: warning

linter:
  rules:
    avoid_shadowing_type_parameters: true
    await_only_futures: true
    empty_catches: true
    null_closures: true
    use_build_context_synchronously: true

    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_null_aware_operators: true
    use_key_in_widget_constructors: true
    use_super_parameters: true

    prefer_single_quotes: true
    avoid_multiple_declarations_per_line: true
    member_ordering:
      - fields
      - constructors
      - factory-constructors
      - methods

    avoid_print: false
    prefer_const_constructors_in_immutables: false